## Pandas
Pandas is a powerful data manipulating library widely used for data analysis and data cleaning

In [1]:
import pandas as pd
import numpy as np

1. Series: 1D- Array like objects are called Series

In [2]:
series=pd.Series([1,2,3,5,6])
series

0    1
1    2
2    3
3    5
4    6
dtype: int64

In [3]:
series=pd.Series({'a':1,'b':2,'c':3,'d':4})
series

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
arr_=np.array([1,2,3,4,40])
index=np.array(['1','2','3','4','5'])
s=pd.Series(arr_,index=index)
s

1     1
2     2
3     3
4     4
5    40
dtype: int64

In [5]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [6]:
df.describe()

           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000

In [7]:
df['score'].mean()

np.float64(13.5625)

In [8]:
df.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [9]:
df.loc[['a','c','e','f'], ['score','name']]

   score       name
a   12.5  Anastasia
c   16.5  Katherine
e    9.0      Emily
f   20.0    Michael

In [10]:
df[df['attempts']>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [11]:
df.count()

name        10
score        8
attempts    10
qualify     10
dtype: int64

In [12]:
df.ndim

2

In [13]:
df.shape[1]

4

In [14]:
df.shape[0]

10

In [15]:
df[df['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [16]:
# Wrap each condition in parentheses and use &
result = df[(df['score'] > 15) & (df['attempts'] < 2)]
result

    name  score  attempts qualify
j  Jonas   19.0         1     yes

In [17]:

df.at['d','score']=11.5
df.loc['d']

name        James
score        11.5
attempts        3
qualify        no
Name: d, dtype: object

In [18]:
df['attempts'].sum()

np.int64(19)

In [19]:
df['score'].mean()

np.float64(13.333333333333334)

In [33]:
df1=pd.DataFrame({'Key':['A','B','C'],'Value':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D','E'],'Value':[4,5,6,9]})

In [34]:
df1

  Key  Value
0   A      1
1   B      2
2   C      3

In [35]:
df2

  Key  Value
0   A      4
1   B      5
2   D      6
3   E      9

In [36]:
pd.merge(df1,df2,on='Key',how='inner')

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

In [37]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0
4   E      NaN      9.0

In [38]:
pd.merge(df1,df2,on='Key',how='left')

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [39]:
pd.merge(df1,df2,on='Key',how='right')

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6
3   E      NaN        9

In [40]:
df = pd.DataFrame({
    'name': ['A', 'B', 'C'],
    'age': [20, 21, 22]
}, index=['x', 'y', 'z'])

In [41]:
df

  name  age
x    A   20
y    B   21
z    C   22

In [43]:
df.loc['x']

name     A
age     20
Name: x, dtype: object

In [47]:
df.loc['x':'y','name']

x    A
y    B
Name: name, dtype: str

In [48]:
df = pd.DataFrame({
    'name': ['A', 'B', 'C', 'D'],
    'age': [20, 21, 22, 23],
    'marks': [80, 85, 90, 95]
})

In [49]:
df

  name  age  marks
0    A   20     80
1    B   21     85
2    C   22     90
3    D   23     95

In [57]:
df=pd.DataFrame(np.random.randint(1,100,size=(6,4)),columns=['A','B','C','D'])
df.set_index('A',inplace=True)
df

     B   C   D
A
38  83  83  11
10  49  20  79
16  66  85  26
91  40  89  26
28  23  66  40
68  22  49  84

In [62]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,3)),columns=['A','B','C'],index=['x','y','z'])

df.at['x','B']

np.int32(85)

In [65]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,5)),columns=['A','B','C','D','E'],index=['x','y','z'])
df

df['F']=df['A']*df['C']
df

    A   B   C   D   E     F
x  48  86  93  71  67  4464
y  94  50  24  79  47  2256
z  19  89  35  30   6   665

In [66]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,4)),columns=['A','B','C','D'])

row_sum=df.sum(axis=1)
col_sum=df.sum(axis=0)

print(f'Rows: {row_sum} and Columns: {col_sum}')

Rows: 0    306
1    179
2    156
dtype: int64 and Columns: A     91
B    187
C    146
D    217
dtype: int64

# Data Cleaning

In [72]:
df=pd.DataFrame(np.random.randint(1,100,size=(5,3)),columns=['A','B','C'])
df

    A   B   C
0  38  38  59
1  20  28  92
2  43  10  38
3   2  23  80
4  91  68  68

In [73]:
df.iloc[0,1]=np.nan
df.iloc[2,2]=np.nan

df

    A     B     C
0  38   NaN  59.0
1  20  28.0  92.0
2  43  10.0   NaN
3   2  23.0  80.0
4  91  68.0  68.0

In [74]:
df.fillna(df.mean(),inplace=True)
df

    A      B      C
0  38  32.25  59.00
1  20  28.00  92.00
2  43  10.00  74.75
3   2  23.00  80.00
4  91  68.00  68.00

In [79]:
df=pd.DataFrame(np.random.randint(1,100,size=(6,4)),columns=['A','B','C','D'])
df

    A   B   C   D
0  52  49  67  11
1  95  29  14  59
2  76  38  83  67
3  98  71  41  11
4  29  71  83  25
5  40  43  26  42

In [80]:
df.iloc[1, 2] = np.nan
df.iloc[3, 0] = np.nan
df.iloc[5, 1] = np.nan

In [81]:
df

      A     B     C   D
0  52.0  49.0  67.0  11
1  95.0  29.0   NaN  59
2  76.0  38.0  83.0  67
3   NaN  71.0  41.0  11
4  29.0  71.0  83.0  25
5  40.0   NaN  26.0  42

In [82]:
df.dropna(axis=1,inplace=True)
df

    D
0  11
1  59
2  67
3  11
4  25
5  42